[project]
name = "control-plane"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "modal>=1.3.3",
    "python-dotenv>=1.1.0",
]
